name: Merge Docs into All Branches

on:
  push:
    branches:
      - docs

jobs:
  merge-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Merge Docs into All Branches
      run: |
        # Loop through all branches in the repository
        for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
          # Skip the docs branch and the current branch
          if [ "$branch" != "docs" ] && [ "$branch" != "main" ]; then
            git checkout $branch
            git merge docs --no-edit
            git push origin $branch
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
