name: Merge Docs into All Branches

on:
  push:
    branches:
      - documentation

jobs:
  merge-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Merge Docs into All Branches
      run: |
        git config --local user.name "Automerge bot"
        git config --local user.email "bot@example.com"

        for branch in $(git for-each-ref --format='%(refname:short)' | grep "/" | cut -d'/' -f2); do
            if [ "$branch" != "documentation" ] && [ "$branch" != "main" ]; then
                git checkout $branch
                git rebase origin/documentation
                git push
            fi
        done
