name: make django migrations

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you want to test with

    - name: Install Django
      run: |
        python -m pip install --upgrade pip
        pip install django

    - name: Make and migrate migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate